variables:
  # Ownership/permission conflicts in /tmp/terragrunt-download are possible, so set TMPDIR to a path inside the build.
  TMPDIR: "$CI_PROJECT_DIR/gitlab-tmp"

before_script:
  - echo "$TMPDIR"  # So it's visible in the log
  - mkdir "$TMPDIR"

test:
  script:
    - cd modules
    - for module in * ; do terraform validate "$module" ; done

promote:
  stage: deploy
  script:
  - cd "$TMPDIR"
  - git clone --depth 2 git@github.com:gpii-ops/gpii-terraform-live
  - cd gpii-terraform-live
  - git rev-parse HEAD
  - git checkout -b tmp-promote
  - echo "$CI_COMMIT_SHA"  # So it's visible in the log
  - bin/promote-module "$CI_COMMIT_SHA" dev
  - bin/promote-module "$CI_COMMIT_SHA" stg
  - git commit -m "Promote version '$CI_COMMIT_SHA' to envs 'dev' and 'stg'."
  - git checkout master
  - git merge --ff tmp-promote
  - git branch -D tmp-promote
  - git push origin HEAD
  # Until we have a general mechanism to sync github -> gitlab
  - git remote add gitlab git@gitlab.com:gpii-ops/gpii-terraform-live.git
  - git push gitlab HEAD
